version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb+srv://rida:IpkYdNb5x2jJjcn6@cluster0.gm3dmu3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    volumes:
      - ./backend:/app

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: